config/routes.rb
Rails.application.routes.draw do
  resources :time_tracking_logs
  root to: 'time_tracking_logs#index'
  resources :users, only: [:new, :create]

  get '/login'     => 'sessions#new'
	post '/login'    => 'sessions#create'
	delete '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/time_tracking_log.rb
class TimeTrackingLog < ApplicationRecord
  belongs_to :user

  def self.today
    initial_time = Time.current.beginning_of_day
    end_time = Time.current.end_of_day
    where(time_entry: initial_time..end_time).order(time_entry: :asc)
  end

  def self.last_seven_days
    initial_time = Time.current.beginning_of_day - 7.days
    end_time = Time.current.end_of_day
    where(time_entry: initial_time..end_time).order(time_entry: :asc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :time_tracking_logs, dependent: :destroy

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_path, alert: 'Você precisa estar logado para acessar esta página.' if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:login][:email].downcase)
    
    if user && user.authenticate(params[:login][:password]) 
      session[:user_id] = user.id.to_s
      redirect_to root_path, notice: 'Login realizado com sucesso!'
    else
      flash.now.alert = "E-mail ou senha incorretos, tente novamente."
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path, notice: "Você está desconectado!"
  end
end

app/controllers/time_tracking_logs_controller.rb
class TimeTrackingLogsController < ApplicationController
  before_action :set_time_tracking_log, only: [:show, :edit, :update, :destroy]
  before_action :authorize

  def index
    @today_time_log = sum_times(@current_user.try(:time_tracking_logs).try(:today))
    @last_seven_days_time_log = sum_times(@current_user.try(:time_tracking_logs).try(:last_seven_days))
  end

  def show
  end

  def new
    @time_tracking_log = TimeTrackingLog.new
  end

  def edit
  end

  def create
    @time_tracking_log = TimeTrackingLog.new(time_tracking_log_params)
    @time_tracking_log.time_entry = Time.current
    @time_tracking_log.user_id = @current_user.id

    respond_to do |format|
      if @time_tracking_log.save
        format.html { redirect_to time_tracking_logs_path, notice: 'Registro criado com sucesso.' }
        format.json { render :show, status: :created, location: @time_tracking_log }
      else
        format.html { render :new }
        format.json { render json: @time_tracking_log.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @time_tracking_log.update(time_tracking_log_params)
        format.html { redirect_to @time_tracking_log, notice: 'Registro atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @time_tracking_log }
      else
        format.html { render :edit }
        format.json { render json: @time_tracking_log.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @time_tracking_log.destroy
    respond_to do |format|
      format.html { redirect_to time_tracking_logs_url, notice: 'Registro deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    def sum_times(time_entries)
      total_time_in_seconds = 0
      time_entries.each_slice(2) do |double_times|
        if double_times.size === 2
          times = double_times.sort.reverse
          total_seconds = times.first.time_entry - times.last.time_entry
          total_time_in_seconds += total_seconds
        end
      end

      { times: time_entries, total_sum_times: Time.at(total_time_in_seconds).utc.strftime("%H:%M:%S") }
    rescue
      nil
    end

    def set_time_tracking_log
      @time_tracking_log = TimeTrackingLog.find(params[:id])
    end

    def time_tracking_log_params
      params.require(:time_tracking_log).permit(:time_entry, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.email.downcase!
    
    if @user.save
      flash[:notice] = "Conta criada com sucesso!"
      redirect_to root_path
    else
      flash.now.alert = "A conta não pôde ser criada. Por favor, insira um e-mail e senha válidos."
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def br_date(datetime)
    datetime.strftime("%d/%m/%Y")
  end

  def br_time(datetime)
    datetime.strftime("%I:%M%p")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/time_tracking_logs_helper.rb
module TimeTrackingLogsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TraineeTimeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-light bg-light row">
        <a class="navbar-brand" href="/">TimeTracker</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Alterna navegação">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <% if current_user.present? %>
              <li class="nav-item">
                <%= "Conectado como: #{current_user.try(:name)}" %>
                <span class="sr-only">(Página atual)</span>
              </li>
              <li class="nav-item">
                <%= link_to 'Home', root_path %>
              </li>
              <li class="nav-item">
                <%= link_to 'Sair', logout_path, method: :delete %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Home', root_path %>
                <span class="sr-only">(Página atual)</span>
              </li>
              <li class="nav-item">
                <%= link_to 'Entrar', login_path %>
              </li>
              <li class="nav-item">
                <%= link_to 'Criar conta', new_user_path %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>

    <hr>

    <div class="container">
      <% if notice %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      <% end %>
    
      <% if alert %>
        <div class="alert alert-warning" role="alert">
          <%= alert %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/time_tracking_logs/_form.html.erb
<%= form_with(model: time_tracking_log, local: true) do |form| %>
  <% if time_tracking_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_tracking_log.errors.count, "error") %> prohibited this time_tracking_log from being saved:</h2>

      <ul>
      <% time_tracking_log.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field d-none">
    <%= form.label :time_entry %>
    <%= form.datetime_select :time_entry %>
  </div>

  <div class="field d-none">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, value: @current_user.try(:id) %>
  </div>

  <div class="actions">
    <%= form.submit 'Registrar', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/time_tracking_logs/_last_seven_days_time_log.html.erb
<h4>
  Últimos 7 dias
</h4>

<div class='table-responsive'>
  <table class='table'>
    <thead>
      <tr>
        <th>Hora</th>
        <th>Tipo</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% if @last_seven_days_time_log.present? %>
        <% @last_seven_days_time_log[:times].each_with_index do |time_tracking_log, index| %>
          <tr>
            <td><%= br_time(time_tracking_log.time_entry) %></td>
            <td><%= index.even? ? 'Entrada' : 'Saída' %></td>
            <td>
              <%= link_to time_tracking_log, method: :delete, data: { confirm: 'Você tem certeza?' } do %>
                <button class='btn btn-danger btn-sm'>Excluir</button>
              <% end %>
            </td>
          </tr>
        <% end %>
        <tr>
          <td colspan='1'></td>
          <td><b>Total:</b></td>
          <td><%= @last_seven_days_time_log[:total_sum_times] %>h</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/time_tracking_logs/_today_time_log.html.erb
<h4>
  Hoje (<%= "#{br_date(Time.current)}" %>)
</h4>

<div class='table-responsive'>
  <table class='table'>
    <thead>
      <tr>
        <th>Hora</th>
        <th>Tipo</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% if @today_time_log.present? %>
        <% @today_time_log[:times].each_with_index do |time_tracking_log, index| %>
          <tr>
            <td><%= br_time(time_tracking_log.time_entry) %></td>
            <td><%= index.even? ? 'Entrada' : 'Saída' %></td>
            <td>
              <%= link_to time_tracking_log, method: :delete, data: { confirm: 'Você tem certeza?' } do %>
                <button class='btn btn-danger btn-sm'>Excluir</button>
              <% end %>
            </td>
          </tr>
        <% end %>
        <tr>
          <td colspan="1"></td>
          <td><b>Total:</b></td>
          <td><%= @today_time_log[:total_sum_times] %>h</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>
<hr>

app/views/time_tracking_logs/edit.html.erb
<div class='d-flex justify-content-center'>
  <div class='card' style='width: 30rem;'>
    <div class='card-body'>
      <h1>Editing Time Tracking Log</h1>

      <%= render 'form', time_tracking_log: @time_tracking_log %>

      <%= link_to 'Show', @time_tracking_log %> |
      <%= link_to 'Back', time_tracking_logs_path %>
    </div>
  </div>
</div>

app/views/time_tracking_logs/index.html.erb
<h2>Registros de horas</h2>
<hr>

<%= render 'today_time_log' %>

<%= link_to new_time_tracking_log_path do %>
  <button class='btn btn-primary btn-lg btn-block'>Registrar hora</button>
<% end %>

<br>
<br>

<%= render 'last_seven_days_time_log' %>

<br>

app/views/time_tracking_logs/new.html.erb
<div class='d-flex justify-content-center'>
  <div class='card' style='width: 30rem;'>
    <div class='card-body text-center'>
      <h1>Registrar hora</h1>
      <br>
      <%= render 'form', time_tracking_log: @time_tracking_log %>
      <br>
      <%= link_to 'Voltar', time_tracking_logs_path %>
    </div>
  </div>
</div>

app/views/time_tracking_logs/show.html.erb
<p>
  <strong>Data:</strong>
  <%= br_date(@time_tracking_log.time_entry) %>
</p>

<p>
  <strong>Hora:</strong>
  <%= br_time(@time_tracking_log.time_entry) %>
</p>

<%= link_to time_tracking_logs_path do %>
  <button class='btn btn-primary'>Voltar</button>
<% end %>

app/views/users/new.html.erb
<div class='d-flex justify-content-center'>
  <div class='card' style='width: 30rem;'>
    <div class='card-body'>
      <h1>Cadastre-se</h1>

      <%= form_for @user do |f| %>
        <div class='form-group'>
          <%= f.label :name %>
          <%= f.text_field :name, autofocus: true, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :email %>
          <%= f.text_field :email, class: 'form-control' %>
        </div>

        <div class='form-group'>
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <div class='form-group'>
          <%= f.submit 'Cadastrar!', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>